[package]
name = "tnid"
version = "0.0.2"
edition = "2024"
description = "A UUID compatible ID with static type checking"
license = "MIT"
documentation = "https://docs.rs/tnid"
repository = "https://github.com/mkeedlinger/tnid"

[dependencies]
aes = {version = "0.8.4", optional = true}
fpe = {version = "0.6.1", optional = true}
rand = {version = "0.8.5", optional = true}
time = {version = "0.3.36", optional = true}
uuid = {version = "1", optional = true}

[dev-dependencies.uuid]
version = "1"
features = ["v4"]

[dev-dependencies]
proptest = "1.9.0"


[features]
default = ["time", "rand"]
encryption = ["dep:aes", "dep:fpe"]
time = ["dep:time"]
rand = ["dep:rand"]
uuid = ["dep:uuid"]
