[package]
name = "tnid-cli"
version = "0.2.0"
edition = "2024"
description = "CLI tool for working with TNIDs"
license = "MIT"
repository = "https://github.com/mkeedlinger/tnid-rust"
readme = "README.md"
keywords = ["tnid", "uuid", "id", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "tnid"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
tnid = { version = "0.2.0", path = "../tnid", features = ["encryption", "time", "rand", "internals"] }
