[package]
name = "tnid-cli"
version = "0.1.0"
edition = "2024"
description = "A CLI for working with TNIDs"
license = "MIT"

[[bin]]
name = "tnid"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.54", features = ["derive", "env"] }
tnid = { version = "0.1.0", path = "../tnid", features = ["encryption", "time", "rand", "internals"] }
